// Policy constants

export const GET_ALL_POLICIES = 'policy/GET_ALL_POLICIES';
export const GET_ALL_POLICIES_ACTION = 'policy/GET_ALL_POLICIES_ACTION';
export const SET_ALL_POLICIES = 'policy/SET_ALL_POLICIES';

export const GET_POLICY_DETAIL = 'policy/GET_POLICY_DETAIL';
export const GET_POLICY_DETAIL_ACTION = 'policy/GET_POLICY_DETAIL_ACTION';
export const SET_POLICY_DETAIL = 'policy/SET_POLICY_DETAIL';

export const CREATE_POLICY_ACTION = 'policy/CREATE_POLICY_ACTION';
export const UPDATE_POLICY_ACTION = 'policy/UPDATE_POLICY_ACTION';
export const DELETE_POLICY_ACTION = 'policy/DELETE_POLICY_ACTION';
