// Investment constants

export const GET_ALL_INVESTMENTS = 'investment/GET_ALL_INVESTMENTS';
export const GET_ALL_INVESTMENTS_ACTION = 'investment/GET_ALL_INVESTMENTS_ACTION';
export const SET_ALL_INVESTMENTS = 'investment/SET_ALL_INVESTMENTS';

export const GET_INVESTMENT_DETAIL = 'investment/GET_INVESTMENT_DETAIL';
export const GET_INVESTMENT_DETAIL_ACTION = 'investment/GET_INVESTMENT_DETAIL_ACTION';
export const SET_INVESTMENT_DETAIL = 'investment/SET_INVESTMENT_DETAIL';

export const CREATE_INVESTMENT_ACTION = 'investment/CREATE_INVESTMENT_ACTION';
export const UPDATE_INVESTMENT_ACTION = 'investment/UPDATE_INVESTMENT_ACTION';
export const DELETE_INVESTMENT_ACTION = 'investment/DELETE_INVESTMENT_ACTION';

export const SET_INVESTMENT_COUNT = 'investment/SET_INVESTMENT_COUNT';
export const GET_INVESTMENT_COUNT = 'investment/GET_INVESTMENT_COUNT';
