// Borrow constants

export const GET_ALL_BORROWINGS = 'borrow/GET_ALL_BORROWINGS';
export const GET_ALL_BORROWINGS_ACTION = 'borrow/GET_ALL_BORROWINGS_ACTION';
export const SET_ALL_BORROWINGS = 'borrow/SET_ALL_BORROWINGS';

export const GET_BORROWING_DETAIL = 'borrow/GET_BORROWING_DETAIL';
export const GET_BORROWING_DETAIL_ACTION = 'borrow/GET_BORROWING_DETAIL_ACTION';
export const SET_BORROWING_DETAIL = 'borrow/SET_BORROWING_DETAIL';

export const CREATE_BORROW_ACTION = 'borrow/CREATE_BORROW_ACTION';
export const UPDATE_BORROW_ACTION = 'borrow/UPDATE_BORROW_ACTION';
export const DELETE_BORROW_ACTION = 'borrow/DELETE_BORROW_ACTION';

export const SET_BORROW_COUNT = 'borrow/SET_BORROW_COUNT';
export const GET_BORROW_COUNT = 'borrow/GET_BORROW_COUNT';
