// Expense constants

export const GET_ALL_EXPENSES = 'expense/GET_ALL_EXPENSES';
export const GET_ALL_EXPENSES_ACTION = 'expense/GET_ALL_EXPENSES_ACTION';
export const SET_ALL_EXPENSES = 'expense/SET_ALL_EXPENSES';

export const GET_EXPENSE_DETAIL = 'expense/GET_EXPENSE_DETAIL';
export const GET_EXPENSE_DETAIL_ACTION = 'expense/GET_EXPENSE_DETAIL_ACTION';
export const SET_EXPENSE_DETAIL = 'expense/SET_EXPENSE_DETAIL';

export const CREATE_EXPENSE_ACTION = 'expense/CREATE_EXPENSE_ACTION';
export const UPDATE_EXPENSE_ACTION = 'expense/UPDATE_EXPENSE_ACTION';
export const DELETE_EXPENSE_ACTION = 'expense/DELETE_EXPENSE_ACTION';

export const EXPORT_EXPENSE_DATA = 'expense/EXPORT_EXPENSE_DATA';
